### ISSUE TITLE
python2.7: ImportError: No module named builtins

### ISSUE THREAD

**Issue by dfranke76** [tdgrant1/denss#17]
$ denss.py ly01.out 
Traceback (most recent call last):
  File "/apps/prod/denss/latest/bin/denss.py", line 29, in <module>
    import saxstats.saxstats as saxs
  File "/apps/prod/denss/latest/lib/python2.7/site-packages/saxstats/saxstats.py", line 35, in <module>
    from builtins import object, range, map, zip, str
ImportError: No module named builtins

"builtins" is the Pyhton3 name, Python2 requires the pip-package "future" which may not be installed. The following seems to work, though:
try:
  from builtins import object, range, map, zip, str
except ImportError:
  from __builtin__ import object, range, map, zip, str

**Comment by tdgrant1** [comment]
I just pushed a new commit with your suggested [changes](https://github.com/tdgrant1/denss/commit/f9f3ab9c91b2e6c78ed24c86afcb7268fb414e1d). thanks for the bug fix. Does that fix the maketrans error for you also?

**Comment by dfranke76** [comment]
Thanks for the quick update. No, the maketrans issue came after this.

I just noticed, in the line "from builtin import object, range, map, zip, str", the "builtin" should have been preceded and followed by double underscore, but the editor made the module name bold instead. Again with proper "code" tags:

```
-from builtin import object, range, map, zip, str
+from __builtin__ import object, range, map, zip, str
```

**Comment by tdgrant1** [comment]
whoops sorry about that. just pushed that [fix](https://github.com/tdgrant1/denss/commit/01ef8568fa35d8ff2e7f62b345d676479766ab60).  I'll see if I can make a work around for the maketrans issue

**Comment by dfranke76** [comment]
My mistake. Starts up without error now. Thanks!

**Comment by tdgrant1** [comment]
oh okay great. thanks!
