### ISSUE TITLE
Python2:  'str' has no attribute 'maketrans'

### ISSUE THREAD

**Issue by dfranke76** [tdgrant1/denss#19]
$ denss.py -f ly01.out
Traceback (most recent call last):
  File "/apps/prod/denss/latest/bin/denss.py", line 48, in <module>
    args = dopts.parse_arguments(parser)
  File "/apps/prod/denss/latest/lib/python2.7/site-packages/saxstats/denssopts.py", line 121, in parse_arguments
    q, I, sigq, Ifit, file_dmax, isout = saxs.loadProfile(args.file, units=args.units)
  File "/apps/prod/denss/latest/lib/python2.7/site-packages/saxstats/saxstats.py", line 722, in loadProfile
    keys = {key.lower().strip().translate(str.maketrans('','', '_ ')): key for key in list(results.keys())}
  File "/apps/prod/denss/latest/lib/python2.7/site-packages/saxstats/saxstats.py", line 722, in <dictcomp>
    keys = {key.lower().strip().translate(str.maketrans('','', '_ ')): key for key in list(results.keys())}
AttributeError: type object 'str' has no attribute 'maketrans'

stackoverflow tells me that maketrans is only available in Python3.

**Comment by dfranke76** [comment]
To note, since this is the 'str' object, this may be related to my "fix" for issue #17?

**Comment by tdgrant1** [comment]
fixed by [this commit](https://github.com/tdgrant1/denss/commit/01ef8568fa35d8ff2e7f62b345d676479766ab60)

**Comment by dfranke76** [comment]
Misunderstanding. The ImportError on builtins is fixed, the maketrans issue still exists. Sorry.

**Comment by tdgrant1** [comment]
ah okay, I will work on a fix then.

**Comment by tdgrant1** [comment]
turns out denss does not need maketrans, so [I just removed it](https://github.com/tdgrant1/denss/commit/cb0f807ba9c19d11eeb681f4adc10e8539746a22). Let me know if you still run into issues.
