### ISSUE TITLE
denss writes output in data directory by default, not working directory

### ISSUE THREAD

**Issue by dfranke76** [tdgrant1/denss#20]
$ pwd
/some/path/foo
$ ls
ly01.out
$ mkdir bar; cd bar
$ denss.py -f ../ly01.out

I would usually expect the files in the current working directory, here foo/bar, but they are created in foo instead.
This can be worked around with "-o ./someprefix".

**Comment by tdgrant1** [comment]
hmm, I'll have to think about this. Maybe most people would prefer to place the output files in the current directory rather than in the directory location of the input file. I'll have to double check if other scripts are affected by this first, such as those that create directories.

**Comment by tdgrant1** [comment]
I have updated the code to reflect this, commit [here](https://github.com/tdgrant1/denss/commit/13711490ef3b558fd9ffae6697b0249aa07d9b87).
