### ISSUE TITLE
fsc/resolution estimate for near identical models seems off

### ISSUE THREAD

**Issue by dfranke76** [tdgrant1/denss#21]
Easiest way to reproduce: run denss.calcfsc.py with the same .mrc as -ref and -f; the resulting FSC will be constant 1.0, but the resolution estimate given will be 206A. Similar to this (near identical inputs):

```
# 1/resolution, FSC; Resolution=206.2 A
 0.00000e+00  1.00000e+00
 1.00000e-02  9.99979e-01
 2.00000e-02  9.99736e-01
[...]
 4.70000e-01  9.74823e-01
 4.80000e-01  9.65391e-01
```

In the case of (near) identical inputs as used here, it should be rather "less than 2.0"?

**Comment by tdgrant1** [comment]
Indeed it did not handle well the case where the FSC does not ever fall below 0.5. I have just [pushed a fix](https://github.com/tdgrant1/denss/commit/ce9927f074cae54007cf592ccc6e046b72f00c49). Now it will first check if the FSC curve ever falls below 0.5, and if so it will simply print "Resolution: < 2.0 A (maximum possible)", or whatever the actual maximum possible resolution is.  Thanks for the catch.
