### ISSUE TITLE
suggestion: add heuristic to guess the data units if not provided

### ISSUE THREAD

**Issue by dfranke76** [tdgrant1/denss#23]
From experience running DENSS a few times, I take it that the assumption is that the data comes in inverse Angstrom if not specified otherwise? For example, data collected at many Beamlines and submitted to SASBDB quite commonly is stored in inverse nanometer. This can lead to some unfortunate results if it goes unnoticed.

As data in inverse Angstrom rarely exceeds q-values of 1.0, a viable check might be: Use user-supplied units if available; otherwise: if q-max < 1.0, assume inv. Angstrom else inv. nanometer. 

While this will not catch all cases and issues, especially with WAXS, it should cover the vast majority of cases and lead to happy users. And not models with a Dmax of 10A when one would expect 100A ^^

**Comment by tdgrant1** [comment]
Yes, the assumption is in Angstrom. There is an option as you mention to specify the units. I and others have used DENSS many times with wide angle scattering data, so I hesitate to change the default if q>1.0. However, you are right that it is inconvenient to have to then rerun denss for example. So I have updated the denss.mrcops.py script to now take a "--units" option that will allow a user to change the dimensions of an MRC file from angstroms to nm or vice versa. Just pushed commit. Is that sufficient?

**Comment by dfranke76** [comment]
> Is that sufficient?

Maybe? Personally, I'd probably re-run with the correct units anyway, even if I knew about this option.

If usage of WAXS with DENSS is common, then my suggestion would indeed not be helpful. That said, maybe you could make the "units" flag mandatory and the choice explicit for the user? If the wrong units are provided at the command line, no one can complain about implicit assumptions?

**Comment by tdgrant1** [comment]
I'll think about this some more. Maybe a reasonable assumption is that the particle is not too small, i.e. if Dmax < 20 then switch to nm or something. My only issue is then users have to keep track of these changes in denss and I think it's best to make users know what they're doing. I'm not sure if I want to force users to always set units, as angstroms appears to be the most common units for most synchrotron beam lines, but I'll think about that. I will close this for now.
