### ISSUE TITLE
result wrong

### ISSUE THREAD

**Issue by lc123623** [tdgrant1/denss#5]
I'm sorry to disturb you that after running your program, the .mrc file I get is just a cube with no shape information. I wonder if there is something wrong with the function write-mrc.

**Comment by tdgrant1** [comment]
Are you using chimera to display it? If so, by default, in the Volume
Viewer window, there's an option checked labeled "Cap high values at box
faces". If you uncheck that option it should fix it. Also, try changing the
threshold in the Volume Viewer window to something larger (drag the slider
to the right).  Let me know if that helps.

**Comment by tdgrant1** [comment]
closing since no reply for some time.
